#!/bin/bash
### BEGIN INIT INFO
# Provides:          company_daemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Company file management daemon
# Description:       Daemon to manage file operations between directories
### END INIT INFO

# Path to executable
DAEMON="/usr/local/bin/company_daemon"
NAME="company_daemon"
DESC="Company file management daemon"

# Check if daemon exists
test -x $DAEMON || exit 0

case "$1" in
  start)
    echo "Starting $DESC: $NAME"
    $DAEMON start
    ;;
  stop)
    echo "Stopping $DESC: $NAME"
    $DAEMON stop
    ;;
  restart)
    echo "Restarting $DESC: $NAME"
    $DAEMON stop
    sleep 1
    $DAEMON start
    ;;
  status)
    $DAEMON status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0